#pragma once

#include <QString>
#include <vector>
#include <memory>

struct TranslationUnit;

/// @brief Parses the file generated by the console application and extract information.
///
/// Obtain the information about all the CompilationProcess (es) that exists in the file generated by the
/// command line application.
class DataParser
{
public:
    DataParser();
    ~DataParser();

    /// @brief Gets CompilationProcess (es) parsed.
    const std::vector<TranslationUnit> getAllProcesses() const;

    bool parse(const QString &path);

private:
    struct Pimpl;
    std::unique_ptr<Pimpl> _impl;
};
