# https://docs.travis-ci.com/user/ci-environment/
# https://docs.travis-ci.com/user/languages/cpp/

language: cpp
sudo: required
dist: trusty

compiler: 
    - gcc
    - clang

before_install:
    # g++4.8
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

    # Cmake
    # - sudo add-apt-repository -y ppa:kalakris/cmake

    - sudo apt-get update -qq

install:
    - export SRC_DIR=$PWD
    # g++4.8
    - if [ "$CXX" = "g++" ]; then sudo apt-get install --allow-unauthenticated -qq g++-4.8 gcc-4.8; fi
    - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 80 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8 --slave /usr/bin/gcov gcov /usr/bin/gcov-4.8; fi

    # CMake newest version
    - sudo apt-get install -qq cmake qt4-dev-tools

    # Install lcov
    #- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz -O /tmp/lcov.tar.gz
    #- cd /tmp/ && tar xf lcov.tar.gz
    #- sudo make -C lcov-1.11/ install      

before_script:
    - export SRC_DIR=$PWD && mkdir build && export BIN_DIR=$PWD
    - bash travis/cmake.sh

script:
    - cd build
    - make
    - bin/test
      # - if [ "$CXX" = "g++" ]; then coveralls -E "/usr/.*" -E "build/*.h" -E ".*/CMakeFiles/.*" --root $SRC_DIR --build-root $BIN_DIR;  fi
