message( STATUS "------------------ General configuration for ${PROJECT_NAME} ${VERSION} -----------------")
message( STATUS )
message( STATUS "Build mode:                ${CMAKE_BUILD_TYPE}")
message( STATUS "CMake Generator:           ${CMAKE_GENERATOR}")
message( STATUS "Compiler:                  ${CMAKE_CXX_COMPILER_ID}")
message( STATUS "CMAKE_SYSTEM_PROCESSOR=    ${CMAKE_SYSTEM_PROCESSOR}" )
message( STATUS "CMAKE_SYSTEM_VERSION=      ${CMAKE_SYSTEM_VERSION}")
message( STATUS "CMAKE_CXX_COMPILER_ID=     ${CMAKE_CXX_COMPILER_ID}")
message( STATUS "CMAKE_CXX_COMPILER=        ${CMAKE_CXX_COMPILER}")
message( STATUS "CMAKE_CXX_COMPILER_VERSION=${CMAKE_CXX_COMPILER_VERSION}")
message( STATUS "C++ flags (Release):       ${CMAKE_CXX_FLAGS_RELEASE}")
message( STATUS "C++ flags (Debug):         ${CMAKE_CXX_FLAGS_DEBUG}")
message( STATUS "C++ flags (Both):          ${CMAKE_CXX_FLAGS}")
message( STATUS )
message( STATUS "---------------------------------------------------------" )
message( STATUS "WARNINGS_ANSI_ISO=         ${WARNINGS_ANSI_ISO}" )
message( STATUS "WARNINGS_ARE_ERRORS=       ${WARNINGS_ARE_ERRORS}" )
message( STATUS "CMAKE_INSTALL_PREFIX=      ${CMAKE_INSTALL_PREFIX}" )
message( STATUS )
message( STATUS "------------------- Documentation  ----------------------" )
message( STATUS )
message( STATUS "INSTALL_DOC=               ${INSTALL_DOC}" )
message( STATUS "USE_LATEX=                 ${USE_LATEX}" )
message( STATUS "USE_DOT=                   ${USE_DOT}" )
message( STATUS "USE_CHM=                   ${USE_CHM}" )
message( STATUS "USE_MATHJAX=               ${USE_MATHJAX}" )
message( STATUS )
message( STATUS "Change a value with: cmake -D<Variable>=<Value>" )
message( STATUS )
